### ISSUE TITLE
Pattern state defaults to "complete"

### ISSUE THREAD

**Issue by perriard** [pattern-lab/patternlab-node#1280]
Hi,

It's just a small thing, but I might as well report it :-)

When creating a new pattern without an appertaining .md file, the pattern state is shown as "complete" (green dot) - the same happens with an incomplete .md file.

I am using Pattern Lab Node v6.14.6 on Mac, with Node v12.18.3, with Twig template engine.

**Expected Behavior**
Blue dot, or no dot as pattern state

**Actual Behavior**
Green dot

**Steps to Reproduce**
no header.md file for the header.twig
or as below in the header.md
```
---
title: Header
state: 
---
```

The below .md produces the blue dot
```
---
title: Header
state: loremipsum
---
```

**Comment by JosefBredereck** [comment]
By default the pattern state is set as 
```scss
.pl-c-pattern-state {
  [...]
  background-color: $pl-color-state-info;

  &--complete {
    background-color: $pl-color-state-complete;
  }

  &--inreview {
    background-color: $pl-color-state-inreview;
  }

  &--inprogress {
    background-color: $pl-color-state-inprogress;
  }

  &--deprecated {
    background-color: $pl-color-state-deprecated;
  }
}
```

Therefore it should already be a blue dot when the state is `!= complete`.
Could you check your code for `.pl-c-pattern-state` mostly old starter kits had set those by themself, which appeared to be located at `source/patterns/css/pattern-scaffolding.css`.
