### ISSUE TITLE
Add overflow-y: auto; for active annotations

### ISSUE THREAD

**Issue by rainbow-pooping-unicorn** [pattern-lab/patternlab-node#624]
I am using Pattern Lab Node `v2.7.2` on `Mac`, with Node `v7.4.0`, using the `Gulp` Edition.

##### Expected Behavior

If a description of an element is longer than the max-height of the container, the user should be able to see all of the content by scrolling within the container.
The max-height is set to 50em and the overflow is hidden at the moment, even if the element is open.

```css
.sg-pattern-extra.active {
    border: 1px solid #ddd;
    border-radius: 6px 0 6px 6px;
    max-height: 50em;
}

.sg-pattern-extra {
    background: #eee;
    border-top: 1px solid #ddd;
    margin-bottom: 1em;
    overflow: hidden;
    max-height: 1px;
    -webkit-transition: all .1s ease-out;
    transition: all .1s ease-out;
}
```

If the annotation is shown (active) the overflow: hidden; should be overwritten with overflow: auto;

```css
.sg-pattern-extra.active {
    border: 1px solid #ddd;
    border-radius: 6px 0 6px 6px;
    max-height: 50em;
    overflow: auto;
}
```

##### Actual Behavior

The Content of the annotation is partly hidden.
<img width="805" alt="bildschirmfoto 2017-02-16 um 08 38 04" src="https://cloud.githubusercontent.com/assets/6604659/23012365/24d37fbc-f426-11e6-899e-e8889c4215f2.png">

##### Steps to Reproduce

1. add a markdownfile to an element
2. fill it with a lot of text for having content in it which will be longer than the max-height of 50em
3. go to your patternlab in the browser and open your element info
